### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by TheJavaScriptWizard** [TheJavaScriptWizard/Satellite_Webmaster_2025#4]
When using px in a website it ruins the scalability of the site, for example if you use a larger monitor the scaling will be incorrect. This is why we should be using rem instead.

[https://dev.to/theodorusclarence/back-to-basic-should-we-use-rem-em-or-pixel-1hd0](url)

**Comment by apathetica** [comment]
The article you sent used `px` for the `rem`, which would yield the same results. I used `vw/vh` instead.

**Comment by apathetica** [comment]
#5
